version: '3'

services:
  hive_app:
    build: ./app/
    container_name: hive_container
    command: php -S 0.0.0.0:80
    ports:
      - "8000:80"
    depends_on:
      - db
  db:
    build: ./database/
    container_name: mysql_container
    image: mysql:5.7
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'hive'
      MYSQL_ROOT_USER: 'root'
      MYSQL_ROOT_PASSWORD: 'Incognito153!'
    ports:
      - '9906:3306'
  jenkins:
    container_name: jenkins_container
    build: ./jenkins/
    ports:
      - "8080:8080"
    depends_on:
      - sonarqube
    environment:
      JENKINS_ADMIN_ID: bart
      JENKINS_ADMIN_PASSWORD: admin
      JENKINS_PORT: 80
    volumes:
      - jenkins-data:/var/jenkins_home
    networks:
      ows-hive:
        aliases:
          - jenkins
  sonarqube:
    container_name: sonarqube_container
    restart: on-failure
    build: ./sonarqube/
    image: sonarqube
    ports:
      - "9000:9000"
    depends_on:
      - db
    networks:
      - ows-hive

volumes:
  jenkins-data:
  mysql-data:

networks:
  ows-hive: